### ISSUE TITLE
FXCM Custom Fields List

### ISSUE THREAD

**Issue by ArneGockeln** [FXCMAPI/FIXAPI#1]
Hi,
where do I get a complete list of custom fields?

In the file https://github.com/fxcm/FIXAPI/blob/master/FXCM%20Custom%20Fields.txt are only a few, but not all.

In a PositionReport message for PosReqType: PosReqType_TRADES are more than described:
9054, 9053, 9048, 9040, 9000

I got only these list from your examples:

```C
  enum FXCM_FIX_FIELDS
  {
    FXCM_SYM_PRECISION         = 9001,
    FXCM_SYM_POINT_SIZE        = 9002,
    FXCM_NO_PARAMS             = 9016,
    FXCM_PARAM_NAME            = 9017,
    FXCM_PARAM_VALUE           = 9018,
    FXCM_REQUEST_REJECT_REASON = 9025,
    FXCM_ERROR_DETAILS         = 9029,
    FXCM_USED_MARGIN           = 9038,
    FXCM_POS_ID                = 9041,
    FXCM_POS_OPEN_TIME         = 9042,
    FXCM_CLOSE_SETTLE_PRICE    = 9043,
    FXCM_POS_CLOSE_TIME        = 9044,
    FXCM_MARGIN_CALL           = 9045,
    FXCM_ORD_TYPE              = 9050,
    FXCM_ORD_STATUS            = 9051,
    FXCM_CLOSE_PNL             = 9052,
    FXCM_PEG_FLUCTUATE_PTS     = 9061,
    FXCM_FIELD_PRODUCT_ID      = 9080,
    FXCM_TRADING_STATUS        = 9096
  };
```
Best Arne

**Comment by ghost** [comment]
Hi,

Please see pages 31- 33  in FXCM-FIX-BSI.pdf

For FIX specification please sign EULA here and you will get it via email
http://www.fxcm.com/uk/forms/eula/


Regards,
Daniel Halpert

**Comment by ArneGockeln** [comment]
Oops. You are right. Sry.
